In [107]:
import pandas as pd
transactions =pd.read_csv(r"C:\@FILES\Projects\Aml Ibm\HI-Small_Trans.csv")

In [108]:
transactions.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,"3,697",US Dollar,"3,697",US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0,US Dollar,0,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,"14,676",US Dollar,"14,676",US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,"2,807",US Dollar,"2,807",US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,"36,683",US Dollar,"36,683",US Dollar,Reinvestment,0

In [109]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078345 entries, 0 to 5078344
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Timestamp           object
 1   From Bank           int64
 2   Account             object
 3   To Bank             int64
 4   Account.1           object
 5   Amount Received     float64
 6   Receiving Currency  object
 7   Amount Paid         float64
 8   Payment Currency    object
 9   Payment Format      object
 10  Is Laundering       int64
dtypes: float64(2), int64(3), object(6)
memory usage: 426.2+ MB

In [114]:
transactions["Timestamp"]=pd.to_datetime(transactions["Timestamp"])
transactions.info()
transactions.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078345 entries, 0 to 5078344
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Timestamp           datetime64[ns]
 1   From Bank           int64
 2   Account             object
 3   To Bank             int64
 4   Account.1           object
 5   Amount Received     float64
 6   Receiving Currency  object
 7   Amount Paid         float64
 8   Payment Currency    object
 9   Payment Format      object
 10  Is Laundering       int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(5)
memory usage: 426.2+ MB

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,"3,697",US Dollar,"3,697",US Dollar,Reinvestment,0
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0,US Dollar,0,US Dollar,Cheque,0
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,"14,676",US Dollar,"14,676",US Dollar,Reinvestment,0
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,"2,807",US Dollar,"2,807",US Dollar,Reinvestment,0
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,"36,683",US Dollar,"36,683",US Dollar,Reinvestment,0

In [124]:
transactions=transactions.rename(columns={"Account":"From Account","Account.1":"To Account"})
transactions.head()

,Timestamp,From Bank,From Account,To Bank,To Account,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,"3,697",US Dollar,"3,697",US Dollar,Reinvestment,0
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0,US Dollar,0,US Dollar,Cheque,0
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,"14,676",US Dollar,"14,676",US Dollar,Reinvestment,0
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,"2,807",US Dollar,"2,807",US Dollar,Reinvestment,0
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,"36,683",US Dollar,"36,683",US Dollar,Reinvestment,0